CREATE TABLE USER (
  USER_ID VARCHAR(32) IDENTITY NOT NULL PRIMARY KEY,
  USER_NAME varchar(32) NOT NULL,
  EMAIL varchar(100) NOT NULL,
  PASSWORD varchar(32) NOT NULL
);

ALTER TABLE user ADD CONSTRAINT UNIQUE_USER_ID UNIQUE (USER_ID);

